### ISSUE TITLE
Implement Lightbox mode

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-datatrans#1]
As a manager, I want to install vc-module-datatrans in Lightbox mode.

Lightbox mode - https://www.datatrans.ch/showcase/authorisation/lightbox-mode.

The Lightbox approach uses an iframe to embed the payment pages as an overlay to your online shop. When the Lightbox Mode is invoked the merchants online shop is darkened out and the payment page appears as a floating element on top.

### Definition of Done
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

### Tasks
- [x] Implement Payment method in Lightbox mode
- [x] Create Read.me file how to configure payment method
- [ ] Publish release 1.0
- [ ] Activate payment on VC demo
